version: "2"
services:
  frontend:
    build: .
    image: mistivit/frontend
    command: npm run prod
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
